config/routes.rb
Rails.application.routes.draw do
  root 'requests#index'
  resources :requests

end

app/models/request.rb
class Request < ActiveRecord::Base
  validates :urgency_scale, presence: true
  validates :location, presence: true
  validates :category, presence: true
  validates :description, presence: true
  validates :actions_attempted, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def new
  @request = Request.new
  end

  def create
  @request = Request.new(request_params)
    if @request.save
    flash[:success] = "Thanks, we'll check it out!"
    render 'new'
    else
    flash[:danger] = "Please try to submit your request again."
    render 'new'
    end
  end

  def update
    @request = Request.find_by(params[:id])
    if @request.update_attributes(request_params)
      flash[:success] = "Your request has been updated."
      render 'update'
    else
      flash[:danger] = "Your request could not be submitted."
      render 'update'
    end
  end

  def delete
    @request = Request.find_by(params[:id])
    @request.destroy
      flash[:success] = "Your request has been deleted."
  end

  def index
    @requests = Request.all
    render :json => @requests
  end

  def request_params
    params.require(:request).permit(:urgency_scale, :location, :category, :description, :actions_attempted)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MaintenanceApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/requests/index.html.erb
<h2> Maintenance Requests </h2>
<p><%= link_to 'Create Request', new_request_path %></p>

app/views/requests/index.json.erb
{
  "requests" : "<%= @requests.urgency_scale.to_json %>"
}

app/views/requests/new.html.erb
<h1> Create New Maintenance Request </h1>
  <%= form_for :request, url: requests_path do |f| %>
    <p>
      <%= f.label :urgency_scale %>
    </p>
    <p>
      <%= f.text_field :urgency_scale %>
    </p>
    <p>
       <%= f.submit %>
    </p>
  <% end %>